### ISSUE TITLE
Add all contributors in readme file 

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Awesome-Javascript-and-React-Project#101]
Add all contributors in the readme file with their photo, name, and GitHub profile link on click of their name

**Comment by SobhanBera** [comment]
Hello @Tejas1510 Can I work on this?

**Comment by Tejas1510** [comment]
Go ahead @SobhanBera 
Just add all the contributor in proper format with proper formating and editing
I would love to merge your work

**Comment by SobhanBera** [comment]
Thanks, But I have a query that can I add contributors at the bottom in rectangular boxes.

**Comment by Tejas1510** [comment]
Add it below the issues part

**Comment by SobhanBera** [comment]
OK I am doing

**Comment by SobhanBera** [comment]
I think this issue is completed so can you close it.
